CREATE TABLE users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   created_by VARCHAR(255),
   created_date TIMESTAMP WITHOUT TIME ZONE,
   last_modified_by VARCHAR(255),
   last_modified_date TIMESTAMP WITHOUT TIME ZONE,
   first_name VARCHAR(255) NOT NULL,
   last_name VARCHAR(255) NOT NULL,
   email VARCHAR(255),
   fax VARCHAR(255),
   last_activity TIMESTAMP WITHOUT TIME ZONE,
   CONSTRAINT pk_users PRIMARY KEY (id)
);

CREATE INDEX idx_user_names ON users(first_name, last_name);

CREATE TABLE posts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   created_by VARCHAR(255),
   created_date TIMESTAMP WITHOUT TIME ZONE,
   last_modified_by VARCHAR(255),
   last_modified_date TIMESTAMP WITHOUT TIME ZONE,
   title VARCHAR(255) NOT NULL,
   text OID NOT NULL,
   published_at TIMESTAMP WITHOUT TIME ZONE,
   author_id BIGINT NOT NULL,
   CONSTRAINT pk_posts PRIMARY KEY (id)
);

ALTER TABLE posts ADD CONSTRAINT fk_posts_on_author FOREIGN KEY (author_id) REFERENCES users (id) ON UPDATE NO ACTION ON DELETE NO ACTION;