services:
  spring-petclinic:
    image: spring-petclinic:latest
    build:
      context: .
      args:
        DOCKER_BUILDKIT: 1
    restart: always
    ports:
      - "8080:8080"
    env_file:
      - prod.env
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8080/actuator/health || exit 1
      interval: 30s
      timeout: 5s
      start_period: 30s
      retries: 5
    depends_on:
      - postgres
  postgres:
    extends:
      service: postgres
      file: services.yaml
    volumes:
      - ./src/main/resources/db/postgres:/docker-entrypoint-initdb.d:ro
    env_file:
      - prod.env
  kafka:
    extends:
      service: kafka
      file: services.yaml
volumes:
  postgres_data:
  kafka_data:
