CREATE TABLE vets (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   first_name TEXT,
   last_name TEXT,
   CONSTRAINT vets_pkey PRIMARY KEY (id)
);

CREATE TABLE specialties (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   name TEXT,
   CONSTRAINT specialties_pkey PRIMARY KEY (id)
);

CREATE TABLE types (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   name TEXT,
   CONSTRAINT types_pkey PRIMARY KEY (id)
);

CREATE TABLE owners (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   first_name TEXT,
   last_name TEXT,
   address TEXT,
   city TEXT,
   telephone TEXT,
   CONSTRAINT owners_pkey PRIMARY KEY (id)
);

CREATE TABLE pets (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   name TEXT,
   birth_date date,
   type_id INTEGER NOT NULL,
   owner_id INTEGER,
   CONSTRAINT pets_pkey PRIMARY KEY (id)
);

CREATE TABLE visits (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   pet_id INTEGER,
   visit_date date,
   description TEXT,
   CONSTRAINT visits_pkey PRIMARY KEY (id)
);

CREATE TABLE vet_specialties (
  vet_id INTEGER NOT NULL,
   specialty_id INTEGER NOT NULL
);

CREATE INDEX vets_last_name_idx ON vets(last_name);

CREATE INDEX specialties_name_idx ON specialties(name);

CREATE INDEX types_name_idx ON types(name);

CREATE INDEX owners_last_name_idx ON owners(last_name);

CREATE INDEX pets_name_idx ON pets(name);

CREATE INDEX pets_owner_id_idx ON pets(owner_id);

CREATE INDEX visits_pet_id_idx ON visits(pet_id);

ALTER TABLE vet_specialties ADD CONSTRAINT vet_specialties_vet_id_specialty_id_key UNIQUE (vet_id, specialty_id);

ALTER TABLE pets ADD CONSTRAINT pets_owner_id_fkey FOREIGN KEY (owner_id) REFERENCES owners (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE pets ADD CONSTRAINT pets_type_id_fkey FOREIGN KEY (type_id) REFERENCES types (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE vet_specialties ADD CONSTRAINT vet_specialties_specialty_id_fkey FOREIGN KEY (specialty_id) REFERENCES specialties (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE vet_specialties ADD CONSTRAINT vet_specialties_vet_id_fkey FOREIGN KEY (vet_id) REFERENCES vets (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE visits ADD CONSTRAINT visits_pet_id_fkey FOREIGN KEY (pet_id) REFERENCES pets (id) ON UPDATE NO ACTION ON DELETE NO ACTION;
